ae_product_analytics:
  target: local
  outputs:
    local:
      type: duckdb
      path: target/ae_product.duckdb
      threads: 4
    ci:
      type: duckdb
      path: target/ae_product_ci.duckdb
      threads: 2
